version: '3'
services:
  cart_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/cart_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_cart
    ports:
      - 15432:5432
  cart:
    build: .
    ports:
      - 9005:9005
    depends_on:
      - cart_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cart_db:5432/db_cart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9005
